service: serverless-typescript-starter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /hello
          method: get
  usersRegister:
    handler: src/users/register.handler
    events:
      - http:
          path: /users/register
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/user_register.json)}
  usersRuth:
    handler: src/users/auth.handler
    events:
      - http:
          path: /users/auth
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/user_logon.json)}

plugins:
  - serverless-esbuild
  - serverless-offline
