service: workshop-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  createUser:
    handler: src/endpoints/user/createUserHandler.handler
    events:
      - httpApi:
          path: /users/register
          method: post
  authUser:
    handler: src/endpoints/user/authUserHandler.handler
    events:
      - httpApi:
          path: /users/auth
          method: post
  createWorkshop:
    handler: src/endpoints/workshop/createWorkshopHandler.handler
    events:
      - httpApi:
          path: /workshops/
          method: post
  getWorkshop:
    handler: src/endpoints/workshop/getWorkshopHandler.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}
          method: get
  listWorkshops:
    handler: src/endpoints/workshop/listWorkshopsHandler.handler
    events:
      - httpApi:
          path: /workshops/
          method: get
  updateWorkshop:
    handler: src/endpoints/workshop/updateWorkshopHandler.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}
          method: put
  deleteWorkshop:
    handler: src/endpoints/workshop/deleteWorkshopHandler.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}
          method: delete
  createParticipation:
    handler: src/participation/createParticipation.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}/participants/
          method: post
  deleteParticipation:
    handler: src/participation/deleteParticipation.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}/participants/
          method: delete
  listParticipants:
    handler: src/participation/listParticipants.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}/participants/
          method: get
  createReview:
    handler: src/review/createReview.handler
    events:
      - httpApi:
          path: /workshops/reviews/
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
