service: serverless-typescript-starter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /hello
          method: get
  userRegister:
    handler: src/users/register.handler
    events:
      - http:
          path: /users/register
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/user_register.json)}
  userAuth:
    handler: src/users/auth.handler
    events:
      - http:
          path: /users/auth
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/user_logon.json)}
  # authorizer:
  #   handler: src/users/authorizer.handler
  #   events:
  addWorkshop:
    handler: src/workshops/addWorkshop.handler
    events:
      - http:
          path: /workshops/
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/add_edit_workshop_request.json)}
  workshopList:
    handler: src/workshops/list.handler
    events:
      - http:
          path: /workshops/
          method: get
          request:
            parameters:
              querystrings:
                status: false
  workshopDetail:
    handler: src/workshops/detail.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}
          method: get
          request:
            parameters:
              paths:
                workshop_UUID: true
  workshopDetailEdit:
    handler: src/workshops/edit.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}
          method: put
          request:
            parameters:
              paths:
                workshop_UUID: true
            schemas:
              application/json: ${file(./src/models/add_edit_workshop_request.json)}
  workshopDelete:
    handler: src/workshops/delete.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}
          method: delete
          request:
            parameters:
              paths:
                workshop_UUID: true
  workshopParticipate:
    handler: src/workshops/participate.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}/participants/{user_email}
          method: post
          request:
            parameters:
              paths:
                workshop_UUID: true
                user_email: true
  workshopCancelParticipate:
    handler: src/workshops/cancelParticipate.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}/participants/{user_email}
          method: delete
          request:
            parameters:
              paths:
                workshop_UUID: true
                user_email: true
  workshopListParticipants:
    handler: src/workshops/listParticipants.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}/participants/
          method: get
          request:
            parameters:
              paths:
                workshop_UUID: true
  workshopPostReview:
    handler: src/workshops/postReview.handler
    events:
      - http:
          path: /workshops/reviews/
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/review_create.json)}

plugins:
  - serverless-esbuild
  - serverless-offline
