service: serverless-typescript-starter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /hello
          method: get
  userRegister:
    handler: src/users/register.handler
    events:
      - http:
          path: /users/register
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/user_register.json)}
  userRuth:
    handler: src/users/auth.handler
    events:
      - http:
          path: /users/auth
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/user_logon.json)}
  workshopCreate:
    handler: src/workshops/create.handler
    events:
      - http:
          path: /workshops/
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/workshop_create.json)}
  workshopList:
    handler: src/workshops/list.handler
    events:
      - http:
          path: /workshops/
          method: get
          request:
            parameters:
              querystrings:
                status: false

plugins:
  - serverless-esbuild
  - serverless-offline
