service: serverless-typescript-starter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  addUser:
    handler: src/users/addUser.handler
    events:
      - httpApi:
          path: /users/register
          method: post
  authUser:
    handler: src/users/authUser.handler
    events:
      - httpApi:
          path: /users/auth
          method: post
  addWorkshop:
    handler: src/workshops/addWorkshop.handler
    events:
      - http:
          path: /workshops/
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/add_edit_workshop_request.json)}
            parameters:
              headers:
                Authorization: true
  getWorkshopDetail:
    handler: src/workshops/getWorkshopDetail.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}
          method: get
          request:
            parameters:
              paths:
                workshop_UUID: true
  listWorkshopDetails:
    handler: src/workshops/listWorkshopDetails.handler
    events:
      - http:
          path: /workshops/
          method: get
          request:
            parameters:
              querystrings:
                status: false
  editWorkshopDetail:
    handler: src/workshops/editWorkshopDetail.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}
          method: put
          request:
            parameters:
              paths:
                workshop_UUID: true
              headers:
                Authorization: true
            schemas:
              application/json: ${file(./src/models/add_edit_workshop_request.json)}
  deleteWorkshop:
    handler: src/workshops/deleteWorkshop.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}
          method: delete
          request:
            parameters:
              paths:
                workshop_UUID: true
              headers:
                Authorization: true
  participateInWorkshop:
    handler: src/workshops/participateInWorkshop.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}/participants/
          method: post
          request:
            parameters:
              paths:
                workshop_UUID: true
              headers:
                Authorization: true
  cancelParticipateInWorkshop:
    handler: src/workshops/cancelParticipateInWorkshop.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}/participants/
          method: delete
          request:
            parameters:
              paths:
                workshop_UUID: true
              headers:
                Authorization: true
  listWorkshopParticipants:
    handler: src/workshops/listWorkshopParticipants.handler
    events:
      - http:
          path: /workshops/{workshop_UUID}/participants/
          method: get
          request:
            parameters:
              paths:
                workshop_UUID: true
              headers:
                Authorization: true
  postWorkshopReview:
    handler: src/workshops/postWorkshopReview.handler
    events:
      - http:
          path: /workshops/reviews/
          method: post
          request:
            schemas:
              application/json: ${file(./src/models/review_create.json)}

plugins:
  - serverless-esbuild
  - serverless-offline
