service: serverless-typescript-starter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  addUser:
    handler: src/users/addUser.handler
    events:
      - httpApi:
          path: /users/register
          method: post
  authUser:
    handler: src/users/authUser.handler
    events:
      - httpApi:
          path: /users/auth
          method: post
  addWorkshop:
    handler: src/workshops/addWorkshop.handler
    events:
      - httpApi:
          path: /workshops/
          method: post
  getWorkshopDetail:
    handler: src/workshops/getWorkshopDetail.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}
          method: get
  listWorkshopDetails:
    handler: src/workshops/listWorkshopDetails.handler
    events:
      - httpApi:
          path: /workshops/
          method: get
  updateWorkshopDetail:
    handler: src/workshops/updateWorkshopDetail.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}
          method: put
  deleteWorkshop:
    handler: src/workshops/deleteWorkshop.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}
          method: delete
  createParticipation:
    handler: src/workshops/createParticipation.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}/participants/
          method: post
  deleteParticipation:
    handler: src/workshops/deleteParticipation.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}/participants/
          method: delete
  listParticipants:
    handler: src/workshops/listParticipants.handler
    events:
      - httpApi:
          path: /workshops/{workshop_UUID}/participants/
          method: get
  createReview:
    handler: src/workshops/createReview.handler
    events:
      - httpApi:
          path: /workshops/reviews/
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
